2020-06-19 19:12:50,714 - process: 121604 - Test_case1_add_friend.py - 错误日志 - 140 - Test_case1_add_friend - ERROR - ------出现错误：心跳接口没有取到指令
